source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git']
timezone:    asian/bangkok

permalink: pretty
markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md

