source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git']
timezone:    asian/bangkok

permalink: /:categories/:title
markdown:    kramdown
markdown_ext:  markdown,mkd,mkdn,md

# "So Simple" theme config
# REF : https://github.com/mmistakes/so-simple-theme
title:            Craft Code
description:      Something about coding by crafting.
logo: site-logo.png
url: http://localhost:4000/

# Owner/author information
owner:
  name:           Pattarawat Chortmai
  avatar:         me.png
  # Social networking links used in footer. Update and remove as you like.
  github: goonnow
  instagram: heytitle

google_analytics: UA-42287027-1

links:
  - title: Articles
    url: /articles

